### ISSUE TITLE
YII2-DepDrop Widget: Second level dropdown list shows the "Loading" text but it never returns anything. 

### ISSUE THREAD

**Issue by rupsk1607** [kartik-v/yii2-widgets#205]
Below is my code:
#in VIEW#
```php
// Parent 
echo $form->field($model, 'intContId')->dropDownList($model->CountryList,['id'=>'cat-id']); 
// Child # 1
echo $form->field($model, 'intStateId')->widget(DepDrop::classname(), [
    'options' => ['id'=>'subcat-id'], // ensure at least the preselected value is available
    'pluginOptions'=>[
        'depends'=>['cat-id'],
        'placeholder'=>'Select State...',
        'url'=>Url::to(['/site/subcat'])
    ]
]);
```
#in Model-country#
```php
public static function getOptions(){
        $data=  static::find()->all();
         $value=  array_merge(['Select... '], \yii\helpers\ArrayHelper::map($data, 'intContId','varContName'));
        return $value;
    }
```
#in Model-state#
```php
  public static function getOptionsbyProvince($intContId) {
        $data = static::find()->where(['intContId'=>$intContId])->select(['intStateId','varStateName'])->asArray()->all();
        $value = (count($data) == 0) ? ['' => ''] : $data;

        return $value;
    }
```
#in UserController#
```php
public function actionSubcat() {
          
     $out = [];
        if (isset($_POST['depdrop_parents'])) {
        $parents = $_POST['depdrop_parents'];
        if ($parents != null) {
             $cat_id = $parents[0];
               $out = \frontend\models\state::getOptionsbyProvince($cat_id);

                echo Json::encode(['output' => $out, 'selected' => '']);
                return;
            }
            // the getSubCatList function will query the database based on the
            // cat_id and return an array like below:
            // [
            //    ['id'=>'<sub-cat-id-1>', 'name'=>'<sub-cat-name1>'],
            //    ['id'=>'<sub-cat_id_2>', 'name'=>'<sub-cat-name2>']
            // ]
           
         
    }
    echo Json::encode(['output'=>'', 'selected'=>'']);
}
```
![capture](https://cloud.githubusercontent.com/assets/9715545/5084774/92dcd83c-6f30-11e4-9b2f-2bfc8be77181.PNG)

IN DATABASE 
i have:
tblcountry: intcontid, varcontname
tblstate: intstateid, varstatename, intcontid

Please help me as soon as possible.
Thanx.

**Comment by fwroman** [comment]
I got the solution, you must import the Json class with: "use use yii\helpers\Json;" at the begin of your controller, or instead of it, just put \yii\helpers\Json::encode(......

I hope this helps you

**Comment by dmitrychel** [comment]
My question concerns the strictness of an array returned from the DB in the controller. 

I upload the list of the countries from Vkontakte and their API returns an array where the key is called "title" instead of "name". 

DepDrop does generate options for the select from the list of countries, but the result is
<option val='1'></option>. That's because the key was 'title' and not 'name'.
I checked dependent-dropdown.js, but changing this file didn't help.
Is there a solution ?

**Comment by fwroman** [comment]
First able you must put an alias instead of the name in the query defined in your controller like this:
$countryList = Country::find()->select(['id_country as id', 'tittle as name'])->asArray()->all();
then you should return this data collection $countryList (for example) without using ArrayHelper just like I've shown in the example.

Hope this helps you.

**Comment by kartik-v** [comment]
You can do as @fwroman said.

But with new release of the dependent-dropdown plugin you can control the column names sent via json. You can set [idParam](http://plugins.krajee.com/dependent-dropdown#option-idParam) and [nameParam](http://plugins.krajee.com/dependent-dropdown#option-nameParam) within `pluginOptions` if you want to override the default `id` and `name`.
